config/routes.rb
Rails.application.routes.draw do
  root 'charts#index'

  get 'admin', to: 'charts#new'
  post 'admin', to: 'charts#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rate.rb
class Rate < ApplicationRecord
  validates :name, :buy, :sell, presence: true
  validates :buy, :sell, numericality: true
  validate do
    if self.forced
      self.errors[:forced] << "must be a valid date" unless (DateTime.parse(self.forced.to_s) rescue false)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController

  def index
    rates = Rate.where(name: 'USD').order(created_at: :desc).limit(2)
    @last_usd = rates.first
    @previus_usd = rates.last
    forced_usd = Rate.where(name: 'USD').where('forced >= ?', DateTime.now).order(forced: :desc).first
    if forced_usd
      @last_usd = forced_usd
    end
  end

  def new
    @rate = Rate.where(name: 'USD').where('forced >= ?', DateTime.now).order(forced: :desc).first || Rate.new
  end

  def create
    @rate = Rate.new(rate_params)
    if @rate.save!
      flash[:success] = "Форсированный курс добавлен"
      redirect_to root_path
    end
  end

  private

  def rate_params
    params.require(:rate).permit(:name, :sell, :buy, :forced)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/views/charts/index.html.haml
.container-fluid
  %h1
    Курс доллара за
    = @last_usd.created_at.in_time_zone("Moscow").strftime("%H:%M %d.%m.%Y")
  .row
    .col-md-3
      .avg_usd_sell
        %p
          Продажа:
          = @last_usd.sell
          - case
            - when @last_usd.sell > @previus_usd.sell
              %span{class: "glyphicon glyphicon-arrow-up"}
            - when @last_usd.sell == @previus_usd.sell
              %span{class: "glyphicon glyphicon-sort"}
            - when @last_usd.sell < @previus_usd.sell
              %span{class: "glyphicon glyphicon-arrow-down"}

      .avg_usd_buy
        %p
          Покупка:
          = @last_usd.buy
          - case
            - when @last_usd.buy > @previus_usd.buy
              %span{class: "glyphicon glyphicon-arrow-up"}
            - when @last_usd.buy == @previus_usd.buy
              %span{class: "glyphicon glyphicon glyphicon-sort"}
            - when @last_usd.buy < @previus_usd.buy
              %span{class: "glyphicon glyphicon-arrow-down"}
  .row
    = link_to "Перейти на admin...", admin_path

app/views/charts/new.html.haml
.container
  .row
    %h1
      Введите форсированный курс
    .col-md-2
      = form_for @rate, url: admin_path(@rate), method: :post do |f|
        .row
          = render 'shared/error_messages', object: f.object
        .row
          = f.label :buy, 'Покупка'
          = f.number_field :buy, class: "form-control rate_buy", required: true, step:"0.01"
        .row
          = f.label :sell, 'Продажа'
          = f.number_field :sell, class: "form-control rate_sell", required: true, step:"0.01"
        .row
          = f.label :forced, 'Дата и время'
          #datetimepicker2.input-group.date
            = f.text_field :forced, class: "form-control rate_forced", required: true, placeholder: @rate.forced.to_s, value: @rate.forced.to_s
            %span.input-group-addon
              %span.glyphicon.glyphicon-calendar
        = f.hidden_field :name, value: "USD", class: "rate_name"
        .row
          = f.submit

      .row
        = link_to "Перейти на главную...", root_path

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  .alert{class: "alert-#{key}"}
    = value

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title PotokIoTest
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .JS-headers
      = render 'layouts/flash'
    = yield

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-error
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
      - object.errors.full_messages.each do |msg|
        %li
          * #{msg}